package nl.parrotlync.discovsuite.spigot.model;

public enum WarpGroup {
    VISITOR, WANDERER, TRAVELER, EXPLORER, VOYAGER, ADVENTURER, PIONEER, SPECIAL_VISITOR, TRAINEE,
    CASTMEMBER, IMAGINEER, DEVELOPER, COORDINATOR, LEAD, SUPERVISOR, DIRECTOR
}