package nl.parrotlync.discovsuite.spigot.model;

public enum WarpGroup {
    VISITOR, EMH, BRONZE, SILVER, GOLD, PLATINUM, INFINITE, SPECIALGUEST, TRAINEE, CASTMEMBER,
    MEDIA, IMAGINEER, TECHNICIAN, DEVELOPER, COORDINATOR, LEAD, MANAGER, DIRECTOR
}
