server-name: DiscovServer

messages:
  no-permission: "&cYou don't have permission for this command"
  player-only: "&cYou need to be a player to execute that command!"
  missing-arguments: "&cThe following arguments are missing: &7%s"
  inventory-clear: "&eYour inventory has been cleared"
  flight-enabled: "&aYou can fly! You can &ofly! &r&aYou can &lfly!"
  flight-disabled: "&cFlight has been disabled"
  fly-speed-change: "&aFlying speed set to: &b%s"
  walk-speed-change: "&aWalking speed set to: &b%s"
  chat-channel-changed: "&aYou are now talking in: &b%s"
  message-has-banned-words: "&f[&3DiscovChat&f] &cPlease keep your language clean and safe!"
  add-banned-word: "&b%s &ahas been added to the swear filter!"
  add-excluded-word: "&b%s &ahas been added as an excluded word!"
  nickname-changed: "&aYour nickname is now: &b%s"

formats:
  chat-global: "&f[&d%SERVER%&f] %DISPLAYNAME% &f> %SUFFIX%"
  chat-staff: "&f[&cStaff&f] %DISPLAYNAME%&7: &b"
  chat-local: "&8[&c%SERVER%Chat&8] &7%NAME%&f: "
  chat-management: "&f[&cManagement&f] %DISPLAYNAME%&7: &3"
  staff-alert: "&f[&6StaffAlert&f] &c&l[!]&r &6%NAME% &7on &6%SERVER%&7: &c"
  broadcast: "&f[&a%{}%&f] &b"

database:
  host: ""
  username: ""
  password: ""
  database: ""

disable-join-quit-messages: true
water-teleport-enabled-worlds: []
cauldron-bins-enabled-worlds: []
punch-disabled-worlds: []

scoreboard-settings:
  interval: 50
  max-length: 26
  title: '&dDiscovNetwork'
scoreboard-content: # Please note that double values will not work.
  1:
    - '&m{fill}'
  2:
    - '&dYour rank:'
  3:
    - '%vault_prefix%'
  4:
    - '  '
  5:
    - '&dCurrent Server:'
  6:
    - '&f{server}'
  7:
    - ' '
  8:
    - '&a&o%bungee_total% &r&bplayers Online!'
    - '&a&o%server_online% &r&bplayers on {server}!'
  9:
    - '&f&m{fill}'
  10:
    - '&bdiscov.network'