server-name: DiscovServer

database:
  host: ""
  username: ""
  password: ""
  database: ""

disable-join-quit-messages: true
armor-stand-bin: IRON_PICKAXE(1)
water-teleport-enabled-worlds: []
cauldron-bins-enabled-worlds: []
punch-disabled-worlds: []
nearest-warp-teleport-disabled-worlds: []

build-inventory:
  0: WOOD_AXE
  1: COMPASS

scoreboard-settings:
  interval: 50
  max-length: 26
  title: '&dDiscovNetwork'

scoreboard-content:
  '1':
    - '&m{fill}'
  '2':
    - '&dYour rank:'
  '3':
    - '%luckperms_prefix_element_highest%'
  '4':
    - '&dCurrent Server:'
  '5':
    - '&f{server}'
  '6':
    - ' '
  '7':
    - '&e$ &f%vault_eco_balance%'
  '8':
    - '  '
  '9':
    - '&a%bungee_total% &bplayers Online!'
  '10':
    - '&f&m{fill}'
  '11':
    - '&bdiscov.network'