messages:
  no-permission: "&cYou don't have permission to do that"
  player-only: "&cYou need to be a player to execute that command!"
  missing-arguments: "&cThe following arguments are missing: %s"
  inventory-clear: "&aYour inventory has been cleared!"
  flight-enabled: "&7Flight enabled!"
  flight-disabled: "&7Flight disabled!"
  fly-speed-change: "ยง7Set flying speed to ยง3%s"
  walk-speed-change: "ยง7Set walking speed to ยง3%s"

database:
  host: ""
  username: ""
  password: ""
  database: ""

disable-join-quit-messages: true
water-teleport-enabled-worlds: []
cauldron-bins-enabled-worlds: []
punch-disabled-worlds: []

scoreboard-settings:
  interval: 50
  max-length: 26
  title: '&3@DiscovNetwork'
scoreboard-content: # Please note that double values will not work.
  1:
    - '&m{fill}'
  2:
    - '&dYour rank'
  3:
    - '%vault_prefix%'
  4:
    - '  '
  5:
    - '&dServer'
  6:
    - '&7&oServerName'
  7:
    - ' '
  8:
    - '&d&o%bungee_total% &r&5players Online!'
    - '&d&o%server_online% &r&5players on ServerName!'
  9:
    - '&f&m{fill}'
  10:
    - '&3discov.network'