main: nl.parrotlync.discovsuite.spigot.DiscovSuite
name: DiscovSuite
version: 2.1
description: Suite with default functionality for the Discovery Network
softdepend: [PlaceholderAPI, LuckPerms]
depend: [ParrotPluginManager]
author: ParrotLync
commands:
  fly:
    usage: /fly
    description: Toggle flight
  speed:
    usage: /speed <speed>
    description: Change flying/walking speed
  clearinventory:
    usage: /clearinventory
    description: Clear your inventory
    aliases: [ci]
  staffchat:
    usage: /staffchat [message]
    description: Send a message in Staff chat
    aliases: [sc]
  managementchat:
    usage: /managementchat [message]
    description: Send a message in Management chat
    aliases: [mc]
  staffalert:
    usage: /staffalert <message>
    description: Send a staff alert to the entire network
    aliases: [sa]
  nick:
    usage: /nick <nickname>
    description: Change your nickname
    aliases: [nickname]
  localchat:
    usage: /localchat [message]
    description: Send a message in local chat
    aliases: [lc]
  localbroadcast:
    usage: /localbroadcast <message>
    description: Broadcast a message on your server
    aliases: [lbc]
  warp:
    usage: /warp <name>
    description: Warp to a location
  randomwarp:
    usage: /randomwarp
    description: Teleport to a random warp
  setwarp:
    usage: /setwarp <name>
    description: Creates a new warp at your current location
  delwarp:
    usage: /delwarp <name>
    description: Deletes a warp
  nearby:
    usage: /nearby
    description: Get a list of nearby warps
    aliases: [near]
  warps:
    usage: /warps
    description: Get a list of all warps
  wake:
    usage: /wake <player>
    description: Wake someone up
permissions:
  discovsuite.command.clearinventory:
    default: op
    description: Permission to use the /clearinventory command
  discovsuite.command.fly:
    default: op
    description: Permission to use the /fly command
  discovsuite.command.fly.others:
    default: op
    description: Permission to use the /fly command for other players
  discovsuite.command.localbroadcast:
    default: op
    description: Permission to use the /localbroadcast command
  discovsuite.command.nickname:
    default: op
    description: Permission to use the /nickname command
  discovsuite.command.speed:
    default: op
    description: Permission to use the /speed command
  discovsuite.command.staffalert:
    default: op
    description: Permission to use the /staffalert command
  discovsuite.command.wake:
    default: op
    description: Permission to use the /wake command
  discovsuite.command.warp:
    default: op
    description: Permission to use the /warp command
  discovsuite.command.warp.others:
    default: op
    description: Permission to use the /warp command for other players
  discovsuite.command.setwarp:
    default: op
    description: Permission to use the /setwarp command
  discovsuite.command.delwarp:
    default: op
    description: Permission to use the /delwarp command
  discovsuite.command.warps:
    default: op
    description: Permission to use the /warps command
  discovsuite.command.randomwarp:
    default: op
    description: Permission to use the /randomwarp command
  discovsuite.command.nearby:
    default: op
    description: Permission to use the /nearby command
  discovsuite.chat.local:
    default: op
    description: Permission to use local chat
  discovsuite.chat.staff:
    default: op
    description: Permission to use staff chat
  discovsuite.chat.management:
    description: Permission to use management chat
  discovsuite.socialspy:
    default: op
    description: Permission to receive socialspy
  discovsuite.chat.socialspy.bypass:
    description: Bypass social spy for messages sent by this player
  discovsuite.chat.mute.bypass:
    default: op
    description: Permission to bypass chat mute
  discovsuite.chat.clear.bypass:
    default: op
    description: Permission to bypass chat clear
  discovsuite.chat.filter.notice:
    default: op
    description: Permission to receive notices of chat filter violations
  discovsuite.chat.filter.bypass:
    default: op
    description: Permission to bypass chat filter restrictions
  discovsuite.chat.color:
    default: op
    description: Permission to use color in chat
  discovsuite.chat.placeholders:
    default: op
    description: Permission to use placeholders in chat
  discovsuite.chat.broadcast.showsender:
    default: op
    description: Permission to see who sent a broadcast message
  discovsuite.fly.onjoin:
    default: op
    description: Permission to auto-enable fly onjoin
  discovsuite.op:
    description: Permission to be auto-opped
  discovsuite.punch:
    default: op
    description: Permission to punch punchable players
  discovsuite.punchable:
    default: op
    description: Makes the player punchable
  discovsuite.watertp.bypass:
    default: op
    description: Permission to bypass water teleport